# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "ob-pattern-2.resource.prefix" . }}-ob-bi-worker-statefulset
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: {{ template "ob-pattern-2.resource.prefix" . }}-ob-bi-worker
  serviceName: {{ template "ob-pattern-2.resource.prefix" . }}-ob-bi-worker-headless-service
  template:
    metadata:
      annotations:
        checksum.ob.bi.worker.bin: {{ include (print $.Template.BasePath "/ob-bi/worker/wso2ob-pattern-2-ob-bi-worker-bin.yaml") . | sha256sum }}
        checksum.ob.bi.worker.conf: {{ include (print $.Template.BasePath "/ob-bi/worker/wso2ob-pattern-2-ob-bi-worker-conf.yaml") . | sha256sum }}
      labels:
        deployment: {{ template "ob-pattern-2.resource.prefix" . }}-ob-bi-worker
    spec:
      {{ if .Values.wso2.deployment.dependencies.mysql }}
      initContainers:
        - name: init-ob-db
          image: busybox:1.32
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z wso2ob-rdbms-service-mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL Server has started";']
      {{ end }}
      containers:
        - name: wso2ob-bi-worker
          {{- if .Values.wso2.deployment.ob.bi.worker.dockerRegistry }}
          image: {{ .Values.wso2.deployment.ob.bi.worker.dockerRegistry }}/{{ .Values.wso2.deployment.ob.bi.worker.imageName }}
          {{- $tag := .Values.wso2.deployment.ob.bi.worker.imageTag }}
          {{- if not (eq $tag "") }}{{- printf ":%s" $tag -}}{{- end }}
          {{- else }}
          image: docker.wso2.com/{{ .Values.wso2.deployment.ob.bi.worker.imageName }}:{{ .Values.wso2.deployment.ob.bi.worker.imageTag }}
          {{- end }}
          imagePullPolicy: {{ .Values.wso2.deployment.ob.bi.worker.imagePullPolicy }}
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 9444
            initialDelaySeconds: {{ .Values.wso2.deployment.ob.bi.worker.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.ob.bi.worker.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 7712
            initialDelaySeconds: {{ .Values.wso2.deployment.ob.bi.worker.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.wso2.deployment.ob.bi.worker.readinessProbe.periodSeconds }}
          lifecycle:
            preStop:
              exec:
                command:  ['sh', '-c', '${WSO2_SERVER_HOME}/bin/worker.sh stop']
          resources:
            requests:
              memory: {{ .Values.wso2.deployment.ob.bi.worker.resources.requests.memory }}
              cpu: {{ .Values.wso2.deployment.ob.bi.worker.resources.requests.cpu }}
            limits:
              memory: {{ .Values.wso2.deployment.ob.bi.worker.resources.limits.memory }}
              cpu: {{ .Values.wso2.deployment.ob.bi.worker.resources.limits.cpu }}
          securityContext:
            runAsUser: 802
          ports:
            - containerPort: 7612
              protocol: TCP
            - containerPort: 7712
              protocol: TCP
            - containerPort: 9444
              protocol: TCP
            - containerPort: 8006
              protocol: TCP
            - containerPort: 8007
              protocol: TCP
            - containerPort: 7444
              protocol: TCP
          volumeMounts:
            - name: ob-bi-worker-bin
              mountPath: /home/wso2carbon/wso2-config-volume/wso2/worker/bin/carbon.sh
              subPath: carbon.sh
            - name: ob-bi-worker-conf
              mountPath: /home/wso2carbon/wso2-config-volume/conf/worker/deployment.yaml
              subPath: deployment.yaml
            - name: ob-bi-worker-deployment-siddhi-files
              mountPath: /home/wso2carbon/wso2-config-volume/deployment/siddhi-files/FraudStatusUpdaterApp.siddhi
              subPath: FraudStatusUpdaterApp.siddhi
            - name: ob-bi-worker-deployment-siddhi-files
              mountPath: /home/wso2carbon/wso2-config-volume/deployment/siddhi-files/TRAAccountValidationApp.siddhi
              subPath: TRAAccountValidationApp.siddhi
            - name: ob-bi-worker-deployment-siddhi-files
              mountPath: /home/wso2carbon/wso2-config-volume/deployment/siddhi-files/TRAPaymentValidationApp.siddhi
              subPath: TRAPaymentValidationApp.siddhi
      serviceAccountName: {{ .Values.kubernetes.serviceAccount }}
      {{- if .Values.wso2.deployment.ob.bi.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.wso2.deployment.ob.bi.imagePullSecrets }}
      {{- else if and (not (eq .Values.wso2.subscription.username "")) (not (eq .Values.wso2.subscription.password "")) }}
      imagePullSecrets:
        - name: {{ template "ob-pattern-2.resource.prefix" . }}-wso2-private-registry-creds
      {{- end }}
      volumes:
        - name: ob-bi-worker-bin
          configMap:
            name: {{ template "ob-pattern-2.resource.prefix" . }}-ob-bi-worker-bin
        - name: ob-bi-worker-conf
          configMap:
            name: {{ template "ob-pattern-2.resource.prefix" . }}-ob-bi-worker-conf
        - name: ob-bi-worker-deployment-siddhi-files
          configMap:
            name: {{ template "ob-pattern-2.resource.prefix" . }}-ob-bi-worker-deployment-siddhi-files
