# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

wso2:
  # WSO2 Subscription parameters (https://wso2.com/subscription/)
  # If provided, these parameters will be used to obtain official WSO2 product Docker images available at WSO2 Private Docker Registry (https://docker.wso2.com/)
  # for this deployment
  subscription:
    username: ""
    password: ""

  deployment:
    dependencies:
      # The configuration should be set to be 'true' if a MySQL database should be spawned as a pod within the cluster
      mysql: true
      # Enable NFS dynamic provisioner for Kubernetes
      nfsServerProvisioner: true

    # Persisted and shared runtime artifacts for Open Banking product profiles
    # See official documentation for detailed information
    # - API Manager: https://docs.wso2.com/display/AM260/Common+Runtime+and+Configuration+Artifacts#CommonRuntimeandConfigurationArtifacts-PersistentRuntimeArtifacts
    # - Key Manager: https://docs.wso2.com/display/OB150/Open+Banking+Key+Manager+High+Availability+Deployment#OpenBankingKeyManagerHighAvailabilityDeployment-DeploymentPattern
    persistentRuntimeArtifacts:
      # Kubernetes Storage Class to be used to dynamically provision the relevant Persistent Volumes
      # Only persistent storage solutions supporting ReadWriteMany access mode are applicable (https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
      # Defaults to Kubernetes Storage Class generated using the NFS Server Provisioner (https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner)
      storageClass: &storage_class "nfs"
      # Define configurations for persistent runtime artifacts which are shared between instances of the Open Banking product profiles
      sharedArtifacts:
        # Define capacities for persistent runtime artifacts which are shared between instances of the Open Banking product profiles
        capacity:
          # For secondary user stores shared between the Key Manager profile instances
          userstores: 50M
          # For execution plans shared between the API Manager profile instances
          executionPlans: 20M
          # For synapse artifacts of APIs shared between the API Manager Gateway profile instances
          synapseConfigs: 50M
      # Persistent runtime artifacts for Apache Solr-based indexing
      apacheSolrIndexing:
        # Indicates if persistence of the runtime artifacts for Apache Solr-based indexing is enabled
        # By default, this is disabled
        enabled: false
        # Define capacities for persistent runtime artifact directories
        capacity:
          # For persisting the H2 based local Carbon database file
          carbonDatabase: 50M
          # For persisting the indexed data
          solrIndexedData: 50M

    ob:
      am:
        # Container image configurations
        # If a custom image must be used, uncomment 'dockerRegistry' and provide its value
        # dockerRegistry: ""
        imageName: "wso2-obam"
        imageTag: "1.5.0"
        # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
        imagePullPolicy: Always

        # Indicates whether the container is running
        livenessProbe:
          # Number of seconds after the container has started before liveness probes are initiated
          initialDelaySeconds: 180
          # How often (in seconds) to perform the probe
          periodSeconds: 10
        # Indicates whether the container is ready to service requests
        readinessProbe:
          # Number of seconds after the container has started before readiness probes are initiated
          initialDelaySeconds: 180
          # How often (in seconds) to perform the probe
          periodSeconds: 10

        resources:
          # These are the minimum resource recommendations for running WSO2 API Management product profiles
          # as per official documentation (https://apim.docs.wso2.com/en/latest/install-and-setup/install/installation-prerequisites/)
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "3Gi"
            cpu: "3000m"
          # JVM settings
          # These are the resource allocation configurations associated with the JVM
          # Refer to the official documentation for advanced details (https://apim.docs.wso2.com/en/latest/install-and-setup/install/installation-prerequisites/)
          jvm:
            # Resource allocation for the Java Heap
            heap:
              memory:
                # Initial and minimum Heap size
                xms: "1024m"
                # Maximum Heap size
                xmx: "1024m"

        # Product configurations
        config:
          # Configure workflow server URL for signup workflow (refer to https://docs.wso2.com/display/OB150/Using+the+Signup+Workflow+for+Berlin)
          workflowServerURL: "https://localhost:9445/services/"

        # Configure Ingresses for Open Banking API Manager service
        ingress:
          # Ingress configurations for Open Banking API Manager service
          management:
            # Hostname for Open Banking API Manager Carbon Management Console
            hostname: "am.ob.wso2.com"
            # Annotations for the Open Banking API Manager services Ingress
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/affinity: "cookie"
              nginx.ingress.kubernetes.io/session-cookie-name: "route"
              nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"

          # Ingress configurations for Gateway profile service
          gateway:
            # Hostname for Open Banking API Manager Gateway service
            hostname: "gateway.am.ob.wso2.com"
            # Annotations for the Open Banking API Manager Gateway service Ingress
            annotations:
              kubernetes.io/ingress.class: "nginx"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

      km:
        # Container image configurations
        # If a custom image must be used, uncomment 'dockerRegistry' and provide its value
        # dockerRegistry: ""
        imageName: "wso2-obkm"
        imageTag: "1.5.0"
        # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
        imagePullPolicy: Always

        # Number of deployment replicas
        replicas: 2

        # Indicates whether the container is running
        livenessProbe:
          # Number of seconds after the container has started before liveness probes are initiated
          initialDelaySeconds: 120
          # How often (in seconds) to perform the probe
          periodSeconds: 10
        # Indicates whether the container is ready to service requests
        readinessProbe:
          # Number of seconds after the container has started before readiness probes are initiated
          initialDelaySeconds: 120
          # How often (in seconds) to perform the probe
          periodSeconds: 10

        resources:
          # These are the resource recommendations for running WSO2 Open Banking Key Manager product profile
          # as per official documentation (https://docs.wso2.com/display/OB150/Open+Banking+Key+Manager+High+Availability+Deployment#OpenBankingKeyManagerHighAvailabilityDeployment-Deploymentprerequisites)
          requests:
            # The minimum amount of memory that should be allocated for a Pod
            memory: "3Gi"
            # The minimum amount of CPU that should be allocated for a Pod
            cpu: "3000m"
          limits:
            # The maximum amount of memory that should be allocated for a Pod
            memory: "4Gi"
            # The maximum amount of CPU that should be allocated for a Pod
            cpu: "4000m"
          # JVM settings
          # These are the resource allocation configurations associated with the JVM
          jvm:
            # Resource allocation for the Java Heap
            heap:
              memory:
                # Initial and minimum Heap size
                xms: "2048m"
                # Maximum Heap size
                xmx: "2048m"

        # Configure Ingress for Open Banking Key Manager service
        ingress:
          # Hostname for Open Banking Key Manager service
          hostname: "km.ob.wso2.com"
          # Annotations for the Open Banking Key Manager service Ingress
          annotations:
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            nginx.ingress.kubernetes.io/affinity: "cookie"
            nginx.ingress.kubernetes.io/session-cookie-name: "route"
            nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"

kubernetes:
  # Name of Kubernetes service account
  serviceAccount: "wso2ob-pattern-1-svc-account"

# Override sub chart parameters
mysql-ob:
  mysql:
    persistence:
      storageClass: *storage_class
